input_train_data_path: "data/raw/heart_train.csv"
input_test_data_path: "data/raw/heart_test.csv"
output_train_data_path: "data/processed/train_data.pkl"
output_test_data_path: "data/processed/test_data.pkl"
output_model_path: "models/model.pkl"
output_prediction_path: "models/prediction.csv"
prepare_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"
train_params:
  val_size: 0.2
  random_state: 42
log_file:
