input_train_data_path: "data/raw/heart_train.csv"
input_test_data_path: "data/raw/heart_test.csv"
output_train_data_path: "data/processed/train_data.pkl"
output_test_data_path: "data/processed/test_data.pkl"
output_model_path: "models/model.pkl"
output_prediction_path: "models/prediction.csv"
prepare_params:
  categorical_features:
    - "sex"
  numerical_features:
    - "age"
    - "chol"
  target_col: "target"
train_params:
  val_size: 0.2
  random_state: 42
model_type: "RandomForestClassifier"
model_params: '{"n_estimators": 200, "max_depth": 5}'
log_file:
